// <auto-generated />
using System;
using AgendaMedica.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgendaMedica.Infrastructure.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    partial class AgendaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Aseguradora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CodigoMunicipio")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0)")
                        .HasDefaultValueSql("now() at time zone 'utc'()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp(0)");

                    b.Property<string>("Gerente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("character varying(80)");

                    b.Property<byte>("TipoEntidadId")
                        .HasColumnType("smallint");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UrlRed")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Aseguradora_Codigo");

                    b.HasIndex("CodigoMunicipio");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Aseguradora_Nombre");

                    b.HasIndex("TipoEntidadId")
                        .HasDatabaseName("IX_Aseguradora_TipoEntidad");

                    b.ToTable("Aseguradora", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AseguradoraId")
                        .HasColumnType("integer");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("EstadoCitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0)")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp(0)");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("timestamp(0)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp(0)");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MotivoConsulta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamsEventId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TeamsJoinUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TipoCitaId")
                        .HasColumnType("integer");

                    b.Property<byte?>("TipoUsuarioId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("AseguradoraId");

                    b.HasIndex("TeamsEventId")
                        .HasDatabaseName("IX_Cita_TeamsEventId")
                        .HasFilter("\"TeamsEventId\" IS NOT NULL");

                    b.HasIndex("TipoCitaId");

                    b.HasIndex("TipoUsuarioId");

                    b.HasIndex("EstadoCitaId", "FechaHora")
                        .HasDatabaseName("IX_Cita_Estado_Fecha");

                    b.HasIndex("PacienteId", "FechaHora")
                        .HasDatabaseName("IX_Cita_Paciente_Fecha");

                    b.HasIndex("ProfesionalId", "FechaHora")
                        .HasDatabaseName("IX_Cita_Profesional_Fecha");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProfesionalId", "FechaHora"), new[] { "PacienteId", "TipoCitaId", "EstadoCitaId", "TeamsEventId" });

                    b.ToTable("Cita", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cita_Fechas", "\"FechaHoraFin\" > \"FechaHora\"");
                        });
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Departamento", b =>
                {
                    b.Property<string>("CodigoDane")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("CodigoDane");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Departamento_Nombre");

                    b.ToTable("Departamento", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.DisponibilidadProfesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ConsultorioSala")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte>("DiaSemana")
                        .HasColumnType("smallint");

                    b.Property<short>("DuracionMinutos")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer");

                    b.Property<int?>("SedeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfesionalId", "DiaSemana")
                        .HasDatabaseName("IX_Disponibilidad_Profesional_Dia");

                    b.ToTable("DisponibilidadProfesional", null, t =>
                        {
                            t.HasCheckConstraint("CK_Disponibilidad_Duracion", "\"DuracionMinutos\" BETWEEN 5 AND 480");

                            t.HasCheckConstraint("CK_Disponibilidad_Rango", "\"HoraFin\" > \"HoraInicio\"");
                        });
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0)")
                        .HasDefaultValueSql("now() at time zone 'utc'()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp(0)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Especialidad", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.EstadoCitaCatalogo", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadoCita", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.HistorialEstadoCita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CambiadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CitaId")
                        .HasColumnType("integer");

                    b.Property<byte?>("EstadoAnteriorId")
                        .HasColumnType("smallint");

                    b.Property<byte>("EstadoNuevoId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0)")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("App");

                    b.HasKey("Id");

                    b.HasIndex("CitaId", "FechaCambio")
                        .HasDatabaseName("IX_HistorialCita_CitaId");

                    b.ToTable("HistorialEstadoCita", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Municipio", b =>
                {
                    b.Property<string>("CodigoDane")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("CodigoDepartamento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(15,9)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(15,9)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("Municipio");

                    b.HasKey("CodigoDane");

                    b.HasIndex("CodigoDepartamento")
                        .HasDatabaseName("IX_Municipio_Departamento");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Municipio_Nombre");

                    b.ToTable("Municipio", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.NotificacionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CitaId")
                        .HasColumnType("integer");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0)")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<byte>("Intentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UltimoIntento")
                        .HasColumnType("timestamp(0)");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("Estado", "Canal", "Intentos")
                        .HasDatabaseName("IX_Notificacion_Pendiente")
                        .HasFilter("\"Estado\" = 'Pendiente'");

                    b.ToTable("NotificacionLog", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.OutboxMensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CitaId")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0)")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTime?>("FechaProcesado")
                        .HasColumnType("timestamp(0)");

                    b.Property<byte>("Intentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<bool>("Procesado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UltimoIntento")
                        .HasColumnType("timestamp(0)");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("Procesado", "Intentos")
                        .HasDatabaseName("IX_Outbox_Pendiente")
                        .HasFilter("\"Procesado\" = false");

                    b.ToTable("OutboxMensaje", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("AseguradoraId")
                        .HasColumnType("integer");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("NombresCompletos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<char>("Sexo")
                        .IsUnicode(false)
                        .HasColumnType("char(1)");

                    b.Property<byte>("TipoIdentificacionId")
                        .HasColumnType("smallint");

                    b.Property<byte?>("TipoUsuarioId")
                        .HasColumnType("smallint");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AseguradoraId");

                    b.HasIndex("TipoUsuarioId");

                    b.HasIndex("TipoIdentificacionId", "NumeroIdentificacion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Paciente_Identificacion");

                    b.ToTable("Paciente", null, t =>
                        {
                            t.HasCheckConstraint("CK_Paciente_FechaNac", "\"FechaNacimiento\" <= CURRENT_DATE");

                            t.HasCheckConstraint("CK_Paciente_Sexo", "\"Sexo\" IN ('M','F')");
                        });
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Profesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConsultorioSala")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NombresCompletos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RegistroMedico")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.Property<byte>("TipoIdentificacionId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("SedeId");

                    b.HasIndex("TipoIdentificacionId", "NumeroIdentificacion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Profesional_Identificacion");

                    b.ToTable("Profesional", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Sede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Ciudad")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0)")
                        .HasDefaultValueSql("now() at time zone 'utc'()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp(0)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Sede", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.TipoCita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("character varying(60)");

                    b.Property<short>("DuracionMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)30);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0)")
                        .HasDefaultValueSql("now() at time zone 'utc'()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp(0)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiereValidacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoCita", null, t =>
                        {
                            t.HasCheckConstraint("CK_TipoCita_Duracion", "[DuracionMinutos] BETWEEN 5 AND 480");
                        });
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.TipoEntidad", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OtroNombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoEntidad", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.TipoIdentificacion", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoIdentificacion", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.TipoUsuario", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoUsuario", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Aseguradora", b =>
                {
                    b.HasOne("AgendaMedica.Domain.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("CodigoMunicipio")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgendaMedica.Domain.Entities.TipoEntidad", "TipoEntidad")
                        .WithMany()
                        .HasForeignKey("TipoEntidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");

                    b.Navigation("TipoEntidad");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Cita", b =>
                {
                    b.HasOne("AgendaMedica.Domain.Entities.Aseguradora", "Aseguradora")
                        .WithMany("Citas")
                        .HasForeignKey("AseguradoraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgendaMedica.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaMedica.Domain.Entities.Profesional", "Profesional")
                        .WithMany("Citas")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaMedica.Domain.Entities.TipoCita", "TipoCita")
                        .WithMany("Citas")
                        .HasForeignKey("TipoCitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaMedica.Domain.Entities.TipoUsuario", "TipoUsuario")
                        .WithMany("Citas")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aseguradora");

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");

                    b.Navigation("TipoCita");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.DisponibilidadProfesional", b =>
                {
                    b.HasOne("AgendaMedica.Domain.Entities.Profesional", "Profesional")
                        .WithMany()
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.HistorialEstadoCita", b =>
                {
                    b.HasOne("AgendaMedica.Domain.Entities.Cita", "Cita")
                        .WithMany("Historial")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("AgendaMedica.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("CodigoDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.NotificacionLog", b =>
                {
                    b.HasOne("AgendaMedica.Domain.Entities.Cita", "Cita")
                        .WithMany("Notificaciones")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.OutboxMensaje", b =>
                {
                    b.HasOne("AgendaMedica.Domain.Entities.Cita", "Cita")
                        .WithMany("OutboxMensajes")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("AgendaMedica.Domain.Entities.Aseguradora", "Aseguradora")
                        .WithMany("Pacientes")
                        .HasForeignKey("AseguradoraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgendaMedica.Domain.Entities.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany("Pacientes")
                        .HasForeignKey("TipoIdentificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaMedica.Domain.Entities.TipoUsuario", "TipoUsuario")
                        .WithMany("Pacientes")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aseguradora");

                    b.Navigation("TipoIdentificacion");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Profesional", b =>
                {
                    b.HasOne("AgendaMedica.Domain.Entities.Especialidad", "Especialidad")
                        .WithMany("Profesionales")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaMedica.Domain.Entities.Sede", "Sede")
                        .WithMany("Profesionales")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaMedica.Domain.Entities.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany("Profesionales")
                        .HasForeignKey("TipoIdentificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Sede");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Aseguradora", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Cita", b =>
                {
                    b.Navigation("Historial");

                    b.Navigation("Notificaciones");

                    b.Navigation("OutboxMensajes");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Especialidad", b =>
                {
                    b.Navigation("Profesionales");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Profesional", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Sede", b =>
                {
                    b.Navigation("Profesionales");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.TipoCita", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.TipoIdentificacion", b =>
                {
                    b.Navigation("Pacientes");

                    b.Navigation("Profesionales");
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.TipoUsuario", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
